### PR TITLE
Update FreeType to 2.12.1 on Mac (x86_64+arm64 binary)

### PR DESCRIPTION
**Pull request by virusman**
Replace the library with a universal binary build that contains both x86_64 and arm64, to be able to make arm64 builds of FSO.

### CODE REVIEW

**Comment by z64555** [comment]
Mmm, not sure what I should be looking out for here.  What all did you do here, and did you need to make any edits to the library or other files?

**Comment by virusman** [comment]
This is to prepare for arm64 support on Mac. The FreeType binary here is x86_64 only, so building an arm64 version of FSO fails on linking with FreeType.

**Comment by z64555** [comment]
Ok, were you able to do tests with these changes on your fork?

**Comment by notimaginative** [comment]
This lib didn't work for me (arm64). It also appears to be a debug build and targets a newer macOS version than what FSO targets.

**Comment by virusman** [comment]
@notimaginative Thanks! Did it not work because you have an older macOS version?

**Comment by notimaginative** [comment]
Oh, sorry, forgot to say that it didn't link due to unresolved symbols (bz2, ... and something else??). The macOS version thing was a warning generated when it tried to link. FSO targets 10.9. I'm something of a novice here though, so I'm not sure how much of an issue that is.

I did managed to generate a working lib, but without png support. I'm not sure if that's really needed however. Here's what I used:
`cmake -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DCMAKE_OSX_DEPLOYMENT_TARGET="10.9" -DCMAKE_BUILD_TYPE=Release -DFT_DISABLE_BZIP2=TRUE -DFT_DISABLE_PNG=TRUE -DFT_DISABLE_HARFBUZZ=TRUE -DFT_DISABLE_BROTLI=TURE ..`

I'm on Ventura btw.

**Comment by notimaginative** [comment]
Closing since it doesn't work properly and there's been no update in a year.

**Pull request closed without merging**
